"""Stub for `liger_kernel.transformers`: the `apply_liger_kernel_to_*` patchers train.py uses."""

from typing import Any

def apply_liger_kernel_to_gemma4(**kwargs: Any) -> None: ...
def apply_liger_kernel_to_qwen3_5(**kwargs: Any) -> None: ...
def apply_liger_kernel_to_qwen3(**kwargs: Any) -> None: ...
